name: everything
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        framework: [ 'net9.0', 'net8.0' ]
        include:
        - os: windows-latest
          framework: net48
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
    - name: Run tests (${{ matrix.framework }})
      run: dotnet test --configuration Release --framework ${{ matrix.framework }} --collect "Code Coverage;Format=cobertura" --results-directory test-results
    - name: Publish coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./test-results/*/*.cobertura.xml
        token: ${{ secrets.CODECOV_TOKEN }}
  package:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
    - name: Create packages (w/o version suffix)
      run: dotnet pack --configuration Release --include-symbols --output ${{ runner.temp }}\pkg
      if: startsWith(github.ref, 'refs/tags/v') == true
    - name: Create packages (w/ version suffix)
      run: dotnet pack --configuration Release --include-symbols --version-suffix preview.${{ github.run_number }} --output ${{ runner.temp }}\pkg
      if: startsWith(github.ref, 'refs/tags/v') != true
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: ${{ runner.temp }}\pkg
    if: github.event_name == 'push'
  prerelease:
    needs: package
    runs-on: windows-latest
    steps:
    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: packages
    - name: Publish packages
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    if: github.ref == 'refs/heads/main'
  release:
    needs: package
    runs-on: windows-latest
    steps:
    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: packages
    - name: Publish packages
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --source nuget.org
    if: startsWith(github.ref, 'refs/tags/v') == true
